import os
import weave
import httpx

APIFY_BASE = "https://api.apify.com/v2"
TOKEN = os.getenv("APIFY_TOKEN", "")
MAX_COMMENTS = int(os.getenv("MAX_COMMENTS", "50"))


def _actor_url(actor_id: str) -> str:
    return f"{APIFY_BASE}/acts/{actor_id}/run-sync-get-dataset-items?token={TOKEN}&timeout=60&memory=512"


@weave.op
async def scrape(url: str) -> dict:
    """Route to the correct scraper based on URL."""
    if "youtube.com" in url or "youtu.be" in url:
        return await _scrape_youtube(url)
    elif "x.com" in url or "twitter.com" in url:
        return await _scrape_x(url)
    raise ValueError(f"Unsupported URL: {url}")


async def _scrape_youtube(url: str) -> dict:
    async with httpx.AsyncClient(timeout=95) as client:
        # 1. Video metadata + transcript
        r = await client.post(
            _actor_url("h7sDV53CddomktSi5"),
            json={
                "startUrls": [{"url": url}],
                "maxResults": 1,
                "downloadSubtitles": True,
                "subtitlesFormat": "plaintext",
                "preferAutoGeneratedSubtitles": True,
                "subtitlesLanguage": "en",
            },
        )
        items = r.json()
        if not isinstance(items, list) or not items or items[0].get("error"):
            raise RuntimeError(f"YouTube scraper failed: {items}")

        item = items[0]
        comments_off = bool(item.get("commentsTurnedOff"))

        # 2. Comments (separate actor)
        raw_comments: list[str] = []
        if not comments_off:
            try:
                rc = await client.post(
                    _actor_url("p7UMdpQnjKmmpR21D"),
                    json={
                        "startUrls": [{"url": url}],
                        "maxComments": MAX_COMMENTS,
                        "sortCommentsBy": "TOP_COMMENTS",
                    },
                    timeout=35,
                )
                for c in rc.json():
                    text = (c.get("comment") or c.get("text") or c.get("textDisplay") or "").strip()
                    if text:
                        raw_comments.append(text)
                raw_comments = raw_comments[:MAX_COMMENTS]
            except Exception:
                pass

        # 3. Subtitles
        subs = item.get("subtitles", "")
        if isinstance(subs, list):
            subtitle_text = " ".join(
                (s.get("plaintext") or s.get("text") or "") for s in subs if isinstance(s, dict)
            ).strip()
        else:
            subtitle_text = str(subs).strip()

        title = item.get("title", "Untitled")
        channel = item.get("channelName") or item.get("channelUsername", "unknown")
        desc = item.get("text") or item.get("description", "")
        primary_text = (
            f"TITLE: {title}\n\nTRANSCRIPT:\n{subtitle_text}"
            if subtitle_text
            else f"TITLE: {title}\n\nDESCRIPTION:\n{desc}"
        )

        return {
            "platform": "youtube",
            "url": url,
            "title": title,
            "creator_handle": f"@{channel.replace(' ', '').lower()}",
            "primary_text": primary_text,
            "raw_comments": raw_comments,
            "comments_unavailable": comments_off or len(raw_comments) == 0,
        }


async def _scrape_x(url: str) -> dict:
    async with httpx.AsyncClient(timeout=65) as client:
        r = await client.post(
            _actor_url("61RPP7dywgiy0JPD0"),
            json={"urls": [url], "maxTweetsPerQuery": 20, "includeReplies": False},
        )
        items = r.json()
        if not isinstance(items, list) or not items:
            raise RuntimeError(f"X scraper returned no results: {items}")

        root = items[0]
        author = (
            (root.get("author") or {}).get("userName")
            or (root.get("user") or {}).get("screen_name", "unknown")
        )
        all_text = "\n\n".join(
            (t.get("text") or t.get("full_text") or "") for t in items
        )
        raw_comments = [
            (t.get("text") or t.get("full_text") or "")
            for t in items[1:]
            if (t.get("text") or t.get("full_text") or "").strip()
        ][:MAX_COMMENTS]

        return {
            "platform": "x",
            "url": url,
            "title": f"Thread by @{author}",
            "creator_handle": f"@{author}",
            "primary_text": f"CREATOR: @{author}\nPLATFORM: X/Twitter\n\nTHREAD:\n{all_text}",
            "raw_comments": raw_comments,
            "comments_unavailable": len(raw_comments) == 0,
        }
