const BASE = 'https://api.apify.com/v2'
const TOKEN = process.env.APIFY_TOKEN!
const MAX_COMMENTS = parseInt(process.env.MAX_COMMENTS ?? '50', 10)

export interface NormalizedContent {
  platform: 'youtube' | 'x'
  contentUrl: string
  creatorHandle: string
  title: string
  primaryText: string
  rawComments: string[]   // existing audience comments from the platform
}

function isYouTubeVideo(url: string): boolean {
  // Must be a specific video: watch?v=, youtu.be/, /shorts/, /live/
  return /youtube\.com\/watch\?.*v=|youtu\.be\/[a-zA-Z0-9_-]+|youtube\.com\/(shorts|live)\//.test(url)
}

function isXPost(url: string): boolean {
  // Must be a specific tweet/post: /status/
  return /x\.com\/.+\/status\/|twitter\.com\/.+\/status\//.test(url)
}

function detectPlatform(url: string): 'youtube' | 'x' | null {
  if (/youtube\.com|youtu\.be/.test(url)) return 'youtube'
  if (/x\.com|twitter\.com/.test(url)) return 'x'
  return null
}

async function runActorSync(
  actorId: string,
  input: Record<string, unknown>,
  timeoutMs = 90_000
): Promise<unknown[]> {
  const res = await fetch(
    `${BASE}/acts/${actorId}/run-sync-get-dataset-items?token=${TOKEN}&timeout=60&memory=512`,
    {
      method: 'POST',
      headers: { 'Content-Type': 'application/json' },
      body: JSON.stringify(input),
      signal: AbortSignal.timeout(timeoutMs),
    }
  )

  if (!res.ok) {
    const text = await res.text()
    throw new Error(`Apify actor ${actorId} failed: ${res.status} ${text}`)
  }

  return res.json() as Promise<unknown[]>
}

export async function scrapeYouTube(url: string): Promise<NormalizedContent> {
  // Fetch video metadata first — we need commentsTurnedOff before deciding
  // whether to call the comments actor at all
  const videoItems = (await runActorSync(
    'h7sDV53CddomktSi5',
    {
      startUrls: [{ url }],
      maxResults: 1,
      downloadSubtitles: true,
      subtitlesFormat: 'plaintext',
      preferAutoGeneratedSubtitles: true,
      subtitlesLanguage: 'en',
    },
    90_000
  )) as Record<string, unknown>[]

  if (!videoItems.length || videoItems[0].error) {
    throw new Error(
      `YouTube scraper returned no results: ${(videoItems[0]?.note as string) ?? ''}`
    )
  }

  const item = videoItems[0]
  const commentsTurnedOff = !!item.commentsTurnedOff

  // Only call the comments actor when comments are actually enabled.
  // If disabled, skip entirely — the actor hangs indefinitely on such videos.
  let rawComments: string[] = []
  if (!commentsTurnedOff) {
    const commentItems = await runActorSync(
      'p7UMdpQnjKmmpR21D',
      {
        startUrls: [{ url }],
        maxComments: MAX_COMMENTS,
        sortCommentsBy: 'TOP_COMMENTS',
      },
      35_000 // hard abort after 35s so a slow video never stalls the whole request
    ).catch(() => [] as unknown[]) as Record<string, unknown>[]

    rawComments = commentItems
      .map((c) => ((c.comment ?? c.text ?? c.textDisplay ?? '') as string).trim())
      .filter((t) => t.length > 0)
      .slice(0, MAX_COMMENTS)
  }

  const subtitleText = extractSubtitles(item)
  const description = (item.text as string) ?? (item.description as string) ?? ''
  const title = (item.title as string) ?? 'Untitled'
  const channelName =
    (item.channelName as string) ?? (item.channelUsername as string) ?? 'unknown'

  const primaryText = subtitleText
    ? `TITLE: ${title}\n\nTRANSCRIPT:\n${subtitleText}`
    : `TITLE: ${title}\n\nDESCRIPTION:\n${description}`

  return {
    platform: 'youtube',
    contentUrl: url,
    creatorHandle: `@${channelName.replace(/\s+/g, '').toLowerCase()}`,
    title,
    primaryText,
    rawComments,
  }
}


function extractSubtitles(item: Record<string, unknown>): string {
  const subtitles = item.subtitles as Record<string, unknown>[] | string | undefined
  if (!subtitles) return ''
  if (typeof subtitles === 'string') return subtitles
  if (Array.isArray(subtitles)) {
    // streamers/youtube-scraper returns [{plaintext, type, language, srtUrl}]
    const fromPlaintext = subtitles
      .map((s) => (typeof s === 'string' ? s : (s.plaintext as string) ?? (s.text as string) ?? ''))
      .join(' ')
    if (fromPlaintext.trim()) {
      return fromPlaintext.replace(/\[.*?\]/g, '').replace(/\s+/g, ' ').trim()
    }
  }
  return ''
}

export async function scrapeXThread(url: string): Promise<NormalizedContent> {
  const items = (await runActorSync('61RPP7dywgiy0JPD0', {
    urls: [url],
    maxTweetsPerQuery: 20,
    includeReplies: false,
  })) as Record<string, unknown>[]

  if (!items.length) throw new Error('X scraper returned no results')

  const root = items[0]
  const author = (root.author as Record<string, string>)?.userName ??
    (root.user as Record<string, string>)?.screen_name ?? 'unknown'

  const allText = items
    .map((t) => (t.text as string) ?? (t.full_text as string) ?? '')
    .filter(Boolean)
    .join('\n\n')

  // Replies to the thread are comments; exclude the root author's own tweets
  const rawComments = items
    .slice(1)
    .map((t) => (t.text as string) ?? (t.full_text as string) ?? '')
    .filter(Boolean)
    .slice(0, MAX_COMMENTS)

  const title = `Thread by @${author}`

  return {
    platform: 'x',
    contentUrl: url,
    creatorHandle: `@${author}`,
    title,
    primaryText: `CREATOR: @${author}\nPLATFORM: X/Twitter\n\nTHREAD:\n${allText}`,
    rawComments,
  }
}

export async function scrapeContent(url: string): Promise<NormalizedContent> {
  const platform = detectPlatform(url)
  if (!platform) throw new Error('Unsupported URL. Paste a YouTube or X/Twitter link.')
  return platform === 'youtube' ? scrapeYouTube(url) : scrapeXThread(url)
}

export { detectPlatform, isYouTubeVideo, isXPost }
